cruise-automation/k-rail

- deploy/helm/templates/validatingwebhook.yaml
This enables `kubectl --server-dry-run` for clusters that support this alpha feature.
Signed-off-by: dustin-decker <dustindecker@protonmail.com>
> enable dry run by specifying side effects

- deploy/helm/templates/deployment.yaml
- deploy/helm/templates/webhooks.yaml
- deploy/helm/values.yaml
- switches deployment to apps/v1
- makes the failurePolicy configurable, and defaults to 'Fail' rather than 'Ignore'
- changes the ValidatingWebhookConfiguration to a MutatingWebhookConfiguration in preparation for new mutating policies
> Deploy improvements

- Dockerfile
Ironically, k-rail won't run in an environment where the default PodSecurityPolicies (PSP) enforce `RunAsNonRoot`, because the USER value in the Dockerfile is non-numeric:
```
Warning  Failed     8s (x4 over 25s)   kubelet, wn3.kube-cluster.local  Error: container has runAsNonRoot and image has non-numeric user (nobody), cannot verify user is non-root
```
This PR simply changes the USER value to the UID of the "nobody" user, and makes PSP happy again :)
> Use numeric USER in Dockerfile for PSP compatibility

- policies/pod/immutable_image_digest.go
- policies/pod/no_new_capabilities.go
- policies/pod/no_privileged_container.go
- policies/pod/no_tiller.go
- policies/pod/trusted_repository.go
This change validates InitContainers in addition to Containers within a PodSpec for policies that iterate containers for violations.
Merging this is a non-backwards compatible change to existing policies so it will result in a new Major release according to semver.
Signed-off-by: dustin-decker <dustindecker@protonmail.com>
> Validate InitContainers

- deploy/non-compliant-daemonset.yaml
- deploy/non-compliant-ingress.yaml
- resource/decoder.go
- resource/ingress.go
- resource/pod.go
Fixes #23.
Improved resource name extraction with `GetResourceName()` which will attempt to retrieve the best resource name, in this order:
1. The name of the controller owner resource (DaemonSet in this case) `.metadata.ownerReferences.name`
1. The top-level `.name` field
1. A name label `.metadata.labels.name`
> Improve resource name extraction

- README.md
- deploy/helm/templates/webhooks.yaml
- deploy/helm/values.yaml
- policies/pod/no_exec.go
- resource/pod_exec.go
- server/policies.go
Adds a policy to block Pod execs unless there is an exemption.
Closes #8.
Signed-off-by: dustin-decker <dustindecker@protonmail.com>
> Add no pod exec policy

- server/server.go
- server/webhook_test.go
Run with default GOMAXPROCS parallelism on an old i7-7500U dual core laptop.
```
go test -benchmem -run=^$ github.com/cruise-automation/k-rail/server -bench .
goos: linux
goarch: amd64
pkg: github.com/cruise-automation/k-rail/server
BenchmarkServer_DenyPolicy-4       	   30000	     43715 ns/op	   50968 B/op	     228 allocs/op
BenchmarkServer_AllowPolicy-4      	   30000	     40958 ns/op	   49825 B/op	     206 allocs/op
BenchmarkServer_AllowExemption-4   	   30000	     46380 ns/op	   51208 B/op	     252 allocs/op
PASS
ok  	github.com/cruise-automation/k-rail/server	5.296s
```
> Add handler + policy + exemption integration test benchmarks

- README.md
- deploy/helm/values.yaml
- policies/config.go
- policies/pod/mutate_default_seccomp_policy.go
- server/policies.go
This policy mutates pods to include a given Seccomp policy by default, unless an exemption is present.
Defaults to `runtime/default`.
```
seccomp.security.alpha.kubernetes.io/pod=runtime/default
```
Closes #15 
Signed-off-by: dustin-decker <dustindecker@protonmail.com>
> Add default seccomp policy

- README.md
- deploy/helm/values.yaml
- policies/pod/no_shareprocessnamespace.go
- server/policies.go
Signed-off-by: Jack Leadford <jack.leadford@nccgroup.com>
See blurb in README.md. This PR adds a default policy that denies use of ShareProcessNamespace, which makes containers in a Pod share a PID namespace.
> Disallow ShareProcessNamespace.

- policies/ingress/require_ingress_exemption.go
- policies/pod/bind_mounts.go
- policies/pod/docker_sock.go
- policies/pod/immutable_image_digest.go
- policies/pod/mutate_default_seccomp_policy.go
- policies/pod/mutate_safe_to_evict.go
- policies/pod/no_exec.go
- policies/pod/no_host_network.go
- policies/pod/no_host_pid.go
- policies/pod/no_new_capabilities.go
- policies/pod/no_privileged_container.go
- policies/pod/no_shareprocessnamespace.go
- policies/pod/no_tiller.go
- policies/pod/safe_to_evict.go
- policies/pod/trusted_repository.go
- resource/context.go
- resource/context_test.go
- resource/ingress.go
- resource/pod.go
- resource/pod_exec.go
- resource/pod_test.go
- server/webhook.go
The policies are executed for each admission request individually. This causes some overhead in decoding the request by each policy as there is no shared state between them. With this PR a simple resource cache is introduced so that the resource types are decoded only once for a request. 
```
goos: darwin
goarch: amd64
pkg: github.com/cruise-automation/k-rail/resource
BenchmarkDecodePodWithoutCaching-4   	   17308	     67706 ns/op
BenchmarkDecodePodCaching-4          	76948933	        15.2 ns/op
PASS
ok  	github.com/cruise-automation/k-rail/resource	3.289s
```
> Proposal for caching admission resources decoding

- README.md
- deploy/helm/values.yaml
- go.mod
- policies/config.go
- policies/config_test.go
- policies/exemption.go
- policies/pod/empty_dir_size_limit.go
- policies/pod/empty_dir_size_limit_test.go
- server/config.go
- server/policies.go
- server/server.go
- server/webhook_test.go
Adds the `PolicyEmptyDirSizeLimit` policy which:
* sets the configured default size when none is set for an `emptyDir` volume
* reports a violation when the size is greater then the configured max size
There is an edge case with a size limit in the volume set to `0`. It is handled like a non set size limit (`nil`).
Resolves #36
> Add EmptyDir size limit policy

- README.md
- deploy/helm/values.yaml
- policies/config.go
- policies/pod/mutate_image_pull_policy.go
- policies/pod/mutate_image_pull_policy_test.go
- server/policies.go
Adding a mutate image pull policy, which enforce certain images matches in the config to use the specified image pull policy:
1> IfNotPresent:
some base image which is shared by most of the pods across the nodes, by enforcing the imagePullPolicy to IfNotPresent can largely reduce the requests to the Image Repository
2>Always:
some image which require extra access should be protected by ImagePullSecret, hence should not allow anyone to use the cached version in the node.
```yaml
policy_config:
mutate_image_pull_policy:
IfNotPresent: 
- '^gcr.io/cruise-gcr-prod/daytona.*'
- '^gcr.io/cruise-gcr-dev/daytona.*'
Always:
- '^gcr.io/private-repo/secretimage.*'
```
> Add a mutate image pull policy

- .github/workflows/main.yml
I don't know if there is any reason to be backwards compatible. There is some practical [issue](https://github.com/cruise-automation/k-rail/pull/54/checks?check_run_id=423126009#step:4:7) with the build flag that I would like to use which was introduced in Go 1.13
> The new go build flag `-trimpath` removes all file system paths from the compiled executable, to improve build reproducibility.
https://golang.org/doc/go1.13#go-command
> Drop Go 1.12.x support in CI

- README.md
There was a newline in the markdown that broke a link. 
Signed-off-by: Jack Leadford <jack.leadford@nccgroup.com>
> Typo fix in the README.

- README.md
- deploy/helm/templates/deployment.yaml
- deploy/helm/values.yaml
Hello!
I added two things to the webhook configuration:
- README context as to the "fail open" vs "fail close" behavior of k-rail, and how to change
this behavior. This **does not** change k-rail's [default behavior](https://github.com/cruise-automation/k-rail/blob/v1.3.1/deploy/helm/values.yaml#L5) of failing closed, just adding some background to
the README so folks are more aware.
- In k8s 1.15+, mutating admission webhooks can specify a `reinvocationPolicy` value in their configuration, which [determines](https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#reinvocation-policy) whether or not to re-invoke the plugin (once) if another admission plugin (like another webhook) modifies an object they did, after the fact. Since this won't be supported …
> Updates to webhook configuration.

- policies/pod/bind_mounts.go
- policies/pod/docker_sock.go
- policies/pod/empty_dir_size_limit.go
- policies/pod/immutable_image_digest.go
- policies/pod/mutate_default_seccomp_policy.go
- policies/pod/mutate_default_seccomp_policy_test.go
- policies/pod/mutate_image_pull_policy.go
- policies/pod/mutate_image_pull_policy_test.go
- policies/pod/mutate_safe_to_evict.go
- policies/pod/no_host_network.go
- policies/pod/no_host_pid.go
- policies/pod/no_new_capabilities.go
- policies/pod/no_privileged_container.go
- policies/pod/no_shareprocessnamespace.go
- policies/pod/no_tiller.go
- policies/pod/safe_to_evict.go
- policies/pod/trusted_repository.go
- resource/pod.go
- resource/pod_test.go
- server/webhook.go
When the Default Seccomp policy (a mutation policy) is enabled, a pod exec will encounter this error:
```
Error from server (InternalError): Internal error occurred: jsonpatch add operation does not apply: doc is missing path: "/metadata/annotations"
```
- Pod resource extraction now ignores execs. This prevents the error encountered during execs when a Pod mutation policy is enabled.
- Adds test for exec request handling for the Pod resource extractor
- Adds test for Default seccomp policy
- Fixes convention of ctx being first arg
> Fix seccomp policy during exec

- policies/ingress/unique_ingress_host.go
This PR is for adding fixes to the Unique Ingress Host Policy from PR #63. It mainly modifies 2 things:
1. Uses a map instead of slice for de-duping on namespaces and improving lookup times
2. Adds the namespaces where the host found to the violationText
> Add namespace to violation text

- deploy/helm/templates/deployment.yaml
- deploy/helm/values.yaml
- deploy/non-compliant-persistent-volume.yaml
- policies/persistentVolume/no_persistent_volume_host.go
- resource/context.go
- resource/persistent_volume.go
- server/policies.go
This PR adds a k-rail policy to ensure that Persistent Volumes cannot specify a Host Path. Enforcing the policy prevents direct access to potentially sensitive files or directories on the Node-level. As [Kubernetes documentation](https://kubernetes.io/docs/tasks/configure-pod-container/configure-persistent-volume-storage/#create-a-persistentvolume) suggests, production clusters should not use HostPath. Instead a cluster administrator would provision a network resource like a Google Compute Engine persistent disk, an NFS share, or an Amazon Elastic Block Store volume. 
This PR also adds a Persistent Volume resource so that k-rail can identify and extract the resource from an AdmissionRequest.
> Add policy to ensure No Persistent Volume HostPath 

- deploy/helm/Chart.yaml
- deploy/helm/templates/deployment.yaml
The helm chart didn't produce a working admission webhook when installing in a namespace other than `k-rail`
This was because the service name and namespace name are transposed in the webhook configuration.
This PR corrects that.
Thanks!
Andy
> Fix bug in helm chart when namespace != k-rail

- charts/k-rail/Chart.yaml
- charts/k-rail/templates/deployment.yaml
Hey guys,
The helm chart for v2.0.0 changed the service port from 443 to 10250 (in https://github.com/cruise-automation/k-rail/commit/ea0c322413a4d682d8ec96d1e0fb1dbe8dfc1711)
As a result, the helm deployment succeeds, but nothing else can be deployed into the cluster because of this:
```
upgrade.go:367: [debug] warning: Upgrade "cert-manager" failed: failed to create resource: Internal error occurred: failed calling webhook "k-rail.cruise-automation.github.com": Post https://k-rail.k-rail.svc:443/?timeout=1s: no service port 443 found for service "k-rail"
Error: UPGRADE FAILED: failed to create resource: Internal error occurred: failed calling webhook "k-rail.cruise-automation.github.com": Post https://k-rail.k-rail.svc:443/?timeout=1s: no service port 443 found for service "k-rail" …
```
> Revert service port to 443

- charts/k-rail/Chart.yaml
- charts/k-rail/templates/deployment.yaml
- charts/k-rail/values.yaml
Hey dudes!
The default webhook timeout of 1s is causing grief for us sometimes, especially when we apply large amounts of manifests at the same time, using `kubectl apply -f <path to directory>`. This change simply adds the option to increase the timeout (which has anecdotally helped in our case), while leaving the default at 1s.
Here's an example of the problem I'm trying to solve:
```
history.go:53: [debug] getting history for release harbor
install.go:172: [debug] Original chart version: "8.0.0"
install.go:189: [debug] CHART PATH: /root/.cache/helm/repository/harbor-8.0.0.tgz
client.go:108: [debug] creating 46 resource(s)
Error: Internal error occurred: failed calling webhook "k-rail.cruise-automation.github.com": Post https://k-rail.k-rail.svc:443/?timeout=1s: context deadline …
```
> Add customizable timeout

- charts/k-rail/Chart.yaml
This should be done when a release is tagged. It's easy to forget, maybe there's a better way to do this?
> Release v3.1.0 of the chart

- server/config.go
- server/metrics.go
- server/policies.go
- server/server.go
- server/server_test.go
- server/webhook.go
Adding policy execution metrics, loaded plugins and registered policies
Example of each in `/metrics` output
```
krail_policy_violations{enforced="true",exempt="false",global_report_only="false",kind="PodExec",namespace="ecommerce",policy="pod_no_exec",report_only="false",resource="payment-processor",user="bob@amyshardware.com"} 1
krail_policy_violations{enforced="false",exempt="false",global_report_only="false",kind="PodExec",namespace="sandbox",policy="pod_no_exec",report_only="true",resource="payment-processor",user="bob@amyshardware.com"} 8
krail_total_loaded_plugins 0
krail_total_registered_policies 23
```
> policy executions with labels in prom metrics

- README.md
- charts/k-rail/Chart.yaml
- charts/k-rail/values.yaml
- examples/non-compliant-daemonset.yaml
- examples/non-compliant-deployment.yaml
- policies/pod/no_root.go
- policies/pod/no_root_test.go
- server/policies.go
Adds a policy to block pods where the `securityContext` will allow a container/pod to run as the root user. An example of a valid securityContext is:
```yaml
securityContext:
runAsUser: 1234
---
securityContext:
runAsNonRoot: true # assumes that the image has an appropriate `USER` directive
```
It can be set at the pod level or at the container level. If set at the container level and not at the pod level, it must be set for all containers (including init containers).
> Added policy to block running as the root user
